# Sentinel Hub Feature Info Service (FIS)

A statistical summary of satellite indices can be requested via the FIS feature. Examples of extracting time-series statistics data of Sentinel-2 and Sentinel-5P indices are provided.<br>

**Note: Cloud mask values have been included along with the obtained statistics values of Sentinel-2 indices in the following examples.**

In [34]:
# import libraries
%matplotlib inline

import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from matplotlib import cm
from shapely.geometry import Polygon
import geopandas as gpd

from sentinelhub import FisRequest, BBox, Geometry, CRS, WcsRequest, CustomUrlParam, \
    DataCollection, HistogramType, bbox_to_dimensions
from sentinelhub.time_utils import iso_to_datetime

In [35]:
# sentinel hub configurations
from sentinelhub import SHConfig


INSTANCE_ID = ''  # In case you put instance ID into configuration file you can leave this unchanged

if INSTANCE_ID:
    config = SHConfig()
    config.instance_id = INSTANCE_ID
else:
    config = None

## Parameters of FIS request


* `layer` -   name of the layer defined in Sentinel Hub Configurator.
* `geometry_list` - list of geometry objects (BBox or Geometry), statistics will be calculated for each of them separately
* `time` - statistics will be calculated for each acquisition in the give time interval separately 
* `resolution` - spatial resolution on which to calculate statistics 
* `data_folder` - optional parameter for specifying location where the data should be saved locally 
* `bins` - The number of bins (a positive integer) in the histogram. When this parameter is absent, no histogram is computed.
* `histogram_type` - ways of dividing values into bins currently supported: EQUIDISTANT, EQUALFREQUENCY, or STREAMING

In [60]:
# NDVI request
def ndvi_request(city_shp, start_date, end_date, city_name):
    geometry = Geometry(city_shp.geometry.values[0], crs=CRS.WGS84)
    time_interval = (start_date, end_date)
    ndvi_stats_fis = FisRequest(
        data_collection=DataCollection.SENTINEL2_L2A,
        layer='NDVI',
        geometry_list=[geometry],
        time=time_interval,
        resolution='100m',
        bins=20, # remove this if distribution values not needed
        histogram_type=HistogramType.EQUIDISTANT, # remove this if distribution values not needed
        config=config
    )
    ndvi_stats = ndvi_stats_fis.get_data()  
    ndvi_stats_df = clean_df(ndvi_stats)
    ndvi_stats_df.to_csv(f'ndvi-{city_name}.csv')
    return ndvi_stats_df

# NDBI request
def ndbi_request(city_shp, start_date, end_date, city_name):
    geometry = Geometry(city_shp.geometry.values[0], crs=CRS.WGS84)
    time_interval = (start_date, end_date)
    ndbi_stats_fis = FisRequest(
        data_collection=DataCollection.LANDSAT_OT_L2,
        layer='NDBI',
        geometry_list=[geometry],
        time=time_interval,
        resolution='100m',
        bins=20, # remove this if distribution values not needed
        histogram_type=HistogramType.EQUIDISTANT, # remove this if distribution values not needed
        config=config
    )
    ndbi_stats = ndbi_stats_fis.get_data()  
    ndbi_stats_df = clean_df(ndbi_stats)
    ndbi_stats_df.to_csv(f'ndbi-{city_name}.csv')
    return ndbi_stats_df

# NO2 request
def no_request(city_shp, start_date, end_date, city_name):
    geometry = Geometry(city_shp.geometry.values[0], crs=CRS.WGS84)
    time_interval = (start_date, end_date)
    no_stats_fis = FisRequest(
        data_collection=DataCollection.SENTINEL5P,
        layer='NO2',
        geometry_list=[geometry],
        time=time_interval,
        resolution='100m',
        config=config
    )
    no_stats = no_stats_fis.get_data()  
    no_stats_df = clean_df(no_stats)
    no_stats_df.to_csv(f'no2-{city_name}.csv')
    return no_stats_df

In [54]:
# convert to clean df ready for analysis
def clean_df (json_stats):
    raw_df_stats = fis_data_to_dataframe(json_stats).reset_index(drop=True)
    index_df = raw_df_stats[raw_df_stats.channel ==0]
    cloud_df = raw_df_stats[raw_df_stats.channel ==1]
    cloud_df = cloud_df.drop(['channel'], axis=1).add_suffix('_clm')
    merged_df = pd.merge(index_df, cloud_df, left_on ='date', right_on = 'date_clm', how='outer')
    clean_merged_df = merged_df.drop(['channel', 'date_clm'], axis=1)
    return clean_merged_df

In [55]:
# load shapefiles of new wave cities

# sta rosa city
sta_rosa = gpd.read_file('nw_cities_shp/Sta Rosa.shp')

# lipa city
lipa = gpd.read_file('nw_cities_shp/Lipa City.shp')

# dasmarinas city
dasmarinas = gpd.read_file('nw_cities_shp/Dasmarinas.shp')

# naga city
naga = gpd.read_file('nw_cities_shp/Naga City.shp')

# baguio city
baguio = gpd.read_file('nw_cities_shp/Baguio.shp')

# CDO city
cdo = gpd.read_file('nw_cities_shp/Cagayan de Oro.shp')

## Sta Rosa City

In [17]:
# ndvi
ndvi_request(sta_rosa,'2021-9-01', '2021-9-30','sta-rosa')

,date,min,max,mean,stDev,min_clm,max_clm,mean_clm,stDev_clm
0,2021-09-04,-1.000000,1.000000,0.158267,0.271893,0.0,1.0,0.965938,0.181389
1,2021-09-09,-1.000000,1.000000,0.501518,0.317544,0.0,1.0,0.059820,0.237154
2,2021-09-14,-1.000000,1.000000,0.523672,0.334050,0.0,1.0,0.037112,0.189037
3,2021-09-19,0.000883,0.038032,0.016582,0.006703,1.0,1.0,1.000000,0.000000
4,2021-09-24,-1.000000,1.000000,0.529691,0.328300,0.0,1.0,0.008304,0.090745
5,2021-09-29,-0.466097,0.840690,0.179279,0.201828,0.0,1.0,0.999322,0.026027

In [62]:
# no2
no_request(sta_rosa,'2021-9-01', '2021-9-30','sta-rosa')

,date,min,max,mean,stDev,min_clm,max_clm,mean_clm,stDev_clm
0,2021-09-01,0.000037,0.000049,0.00004,0.000005,NaN,NaN,NaN,NaN
1,2021-09-02,0.000013,0.000033,0.000032,0.000004,NaN,NaN,NaN,NaN
2,2021-09-03,0.000041,0.000087,0.000086,0.000008,NaN,NaN,NaN,NaN
3,2021-09-04,0.00003,0.000071,0.000041,0.000013,NaN,NaN,NaN,NaN
4,2021-09-05,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,2021-09-06,0.000029,0.000048,0.000033,0.000003,NaN,NaN,NaN,NaN
6,2021-09-07,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,2021-09-08,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,2021-09-09,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,2021-09-10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,2021-09-11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,2021-09-12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,2021-09-13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,2021-09-14,0.000018,0.000041,0.000033,0.000008,NaN,NaN,NaN,NaN
14,2021-09-15,-0.000004,0.000026,0.000012,0.00001,NaN,NaN,NaN,NaN
15,2021-09-16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,2021-09-17,0.000007,0.000017,0.000013,0.000004,NaN,NaN,NaN,NaN
17,2021-09-18,-0.000011,0.000017,0.000007,0.000012,NaN,NaN,NaN,NaN
18,2021-09-19,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,2021-09-20,0.000054,0.000054,0.000054,0.0,NaN,NaN,NaN,NaN
20,2021-09-21,0.000008,0.000026,0.000018,0.000004,NaN,NaN,NaN,NaN
21,2021-09-22,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,2021-09-23,0.000011,0.000025,0.000022,0.000003,NaN,NaN,NaN,NaN
23,2021-09-24,0.00002,0.000035,0.000024,0.000006,NaN,NaN,NaN,NaN
24,2021-09-25,0.000021,0.000034,0.000025,0.000004,NaN,NaN,NaN,NaN
25,2021-09-26,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,2021-09-27,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,2021-09-28,0.000024,0.000063,0.000044,0.000008,NaN,NaN,NaN,NaN
28,2021-09-29,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,2021-09-30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## Lipa City

In [18]:
ndvi_request(lipa,'2021-9-01', '2021-9-30','lipa')

,date,min,max,mean,stDev,min_clm,max_clm,mean_clm,stDev_clm
0,2021-09-04,-1.000000,1.000000,0.445838,0.310395,0.0,1.0,0.741569,0.437772
1,2021-09-09,-1.000000,1.000000,0.345226,0.340423,0.0,1.0,0.828171,0.377232
2,2021-09-14,-1.000000,1.000000,0.613918,0.313166,0.0,1.0,0.325064,0.468399
3,2021-09-19,-0.012875,0.061279,0.015574,0.007428,1.0,1.0,1.000000,0.000000
4,2021-09-24,-1.000000,1.000000,0.501906,0.354422,0.0,1.0,0.446510,0.497131
5,2021-09-29,-0.048028,0.726702,0.336904,0.154124,1.0,1.0,1.000000,0.000000

In [61]:
no_request(lipa,'2021-9-01', '2021-9-30','lipa')

,date,min,max,mean,stDev,min_clm,max_clm,mean_clm,stDev_clm
0,2021-09-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2021-09-02,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2021-09-03,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2021-09-04,0.000018,0.000044,0.000033,0.000007,NaN,NaN,NaN,NaN
4,2021-09-05,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,2021-09-06,0.000015,0.000015,0.000015,0.0,NaN,NaN,NaN,NaN
6,2021-09-07,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,2021-09-08,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,2021-09-09,0.000001,0.000037,0.000022,0.000008,NaN,NaN,NaN,NaN
9,2021-09-10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,2021-09-11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,2021-09-12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,2021-09-13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,2021-09-14,0.00001,0.000046,0.000016,0.000005,NaN,NaN,NaN,NaN
14,2021-09-15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,2021-09-16,-0.000005,0.000018,0.000003,0.000011,NaN,NaN,NaN,NaN
16,2021-09-17,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,2021-09-18,-0.000007,0.000038,0.000004,0.00001,NaN,NaN,NaN,NaN
18,2021-09-19,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,2021-09-20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,2021-09-21,0.000003,0.000024,0.000014,0.000007,NaN,NaN,NaN,NaN
21,2021-09-22,0.000007,0.000036,0.000021,0.000011,NaN,NaN,NaN,NaN
22,2021-09-23,0.000005,0.00002,0.000015,0.000004,NaN,NaN,NaN,NaN
23,2021-09-24,0.000012,0.000039,0.000032,0.000007,NaN,NaN,NaN,NaN
24,2021-09-25,0.000018,0.00003,0.000022,0.000004,NaN,NaN,NaN,NaN
25,2021-09-26,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,2021-09-27,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,2021-09-28,0.000017,0.000073,0.000057,0.000018,NaN,NaN,NaN,NaN
28,2021-09-29,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,2021-09-30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## Dasmarinas City

In [19]:
ndvi_request(dasmarinas,'2021-9-01', '2021-9-30','dasmarinas')

,date,min,max,mean,stDev,min_clm,max_clm,mean_clm,stDev_clm
0,2021-09-04,-1.000000,1.000000,0.397376,0.307945,0.0,1.0,0.784589,0.411107
1,2021-09-09,-0.715496,1.000000,0.281581,0.281444,0.0,1.0,0.934168,0.247988
2,2021-09-14,-1.000000,1.000000,0.548557,0.301314,0.0,1.0,0.217246,0.412371
3,2021-09-19,-0.004112,0.039941,0.019438,0.004796,1.0,1.0,1.000000,0.000000
4,2021-09-24,-1.000000,1.000000,0.578049,0.306945,0.0,1.0,0.084287,0.277817
5,2021-09-29,-0.458382,0.981876,0.353552,0.222547,1.0,1.0,1.000000,0.000000

In [64]:
no_request(dasmarinas,'2021-9-01', '2021-9-30','dasmarinas')

,date,min,max,mean,stDev,min_clm,max_clm,mean_clm,stDev_clm
0,2021-09-01,0.000039,0.000039,0.000039,0.0,NaN,NaN,NaN,NaN
1,2021-09-02,0.000014,0.000041,0.000016,0.000008,NaN,NaN,NaN,NaN
2,2021-09-03,0.000019,0.000052,0.000042,0.000011,NaN,NaN,NaN,NaN
3,2021-09-04,0.000036,0.000051,0.000045,0.000003,NaN,NaN,NaN,NaN
4,2021-09-05,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,2021-09-06,0.000025,0.000075,0.000033,0.000015,NaN,NaN,NaN,NaN
6,2021-09-07,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,2021-09-08,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,2021-09-09,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,2021-09-10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,2021-09-11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,2021-09-12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,2021-09-13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,2021-09-14,0.000026,0.000048,0.000039,0.000007,NaN,NaN,NaN,NaN
14,2021-09-15,0.000014,0.00005,0.00002,0.000007,NaN,NaN,NaN,NaN
15,2021-09-16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,2021-09-17,0.000002,0.000019,0.000014,0.000008,NaN,NaN,NaN,NaN
17,2021-09-18,0.000012,0.00002,0.000017,0.000004,NaN,NaN,NaN,NaN
18,2021-09-19,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,2021-09-20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,2021-09-21,0.000018,0.000034,0.000022,0.000003,NaN,NaN,NaN,NaN
21,2021-09-22,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,2021-09-23,0.000011,0.00003,0.000026,0.000004,NaN,NaN,NaN,NaN
23,2021-09-24,0.000031,0.000038,0.000035,0.000002,NaN,NaN,NaN,NaN
24,2021-09-25,0.000029,0.000063,0.000044,0.000013,NaN,NaN,NaN,NaN
25,2021-09-26,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,2021-09-27,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,2021-09-28,0.000063,0.000063,0.000063,0.0,NaN,NaN,NaN,NaN
28,2021-09-29,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,2021-09-30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## Naga City

In [20]:
ndvi_request(naga,'2021-9-01', '2021-9-30','naga')

,date,min,max,mean,stDev,min_clm,max_clm,mean_clm,stDev_clm
0,2021-09-01,0.019005,0.920455,0.116704,0.066429,1.0,1.0,1.000000,0.000000
1,2021-09-06,-0.052031,0.873513,0.338949,0.218207,1.0,1.0,1.000000,0.000000
2,2021-09-11,-0.018661,0.552433,0.231225,0.127175,1.0,1.0,1.000000,0.000000
3,2021-09-16,-0.128635,1.000000,0.252424,0.151006,0.0,1.0,0.993760,0.078744
4,2021-09-21,-1.000000,1.000000,0.370525,0.348309,0.0,1.0,0.745740,0.435444
5,2021-09-26,-0.137758,1.000000,0.152246,0.216070,0.0,1.0,0.988121,0.108342

In [65]:
no_request(naga,'2021-9-01', '2021-9-30','naga')

,date,min,max,mean,stDev,min_clm,max_clm,mean_clm,stDev_clm
0,2021-09-01,0.000022,0.000026,0.000024,0.000002,NaN,NaN,NaN,NaN
1,2021-09-02,0.000016,0.000021,0.000019,0.000002,NaN,NaN,NaN,NaN
2,2021-09-03,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2021-09-04,0.000011,0.000015,0.000012,0.000002,NaN,NaN,NaN,NaN
4,2021-09-05,0.000016,0.000045,0.000028,0.000014,NaN,NaN,NaN,NaN
5,2021-09-06,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,2021-09-07,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,2021-09-08,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,2021-09-09,0.000009,0.000022,0.000016,0.000006,NaN,NaN,NaN,NaN
9,2021-09-10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,2021-09-11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,2021-09-12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,2021-09-13,0.000002,0.00001,0.000002,0.000001,NaN,NaN,NaN,NaN
13,2021-09-14,0.000005,0.000022,0.000016,0.000006,NaN,NaN,NaN,NaN
14,2021-09-15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,2021-09-16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,2021-09-17,-0.000002,-0.000002,-0.000002,0.0,NaN,NaN,NaN,NaN
17,2021-09-18,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,2021-09-19,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,2021-09-20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,2021-09-21,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,2021-09-22,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,2021-09-23,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,2021-09-24,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,2021-09-25,0.000004,0.000021,0.000017,0.000007,NaN,NaN,NaN,NaN
25,2021-09-26,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,2021-09-27,0.000013,0.000013,0.000013,0.0,NaN,NaN,NaN,NaN
27,2021-09-28,0.000019,0.000019,0.000019,0.0,NaN,NaN,NaN,NaN
28,2021-09-29,0.000029,0.000038,0.00003,0.000003,NaN,NaN,NaN,NaN
29,2021-09-30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## Baguio City

In [21]:
ndvi_request(baguio,'2021-9-01', '2021-9-30','baguio')

,date,min,max,mean,stDev,min_clm,max_clm,mean_clm,stDev_clm
0,2021-09-02,-1.000000,1.000000,0.362709,0.328503,0.0,1.0,0.672821,0.469183
1,2021-09-04,0.014223,0.153574,0.045114,0.017467,1.0,1.0,1.000000,0.000000
2,2021-09-07,-0.842520,1.000000,0.380785,0.312224,0.0,1.0,0.540253,0.498377
3,2021-09-09,-0.448567,1.000000,0.560301,0.254467,0.0,1.0,0.083001,0.275883
4,2021-09-12,0.015342,0.031300,0.024847,0.001861,1.0,1.0,1.000000,0.000000
5,2021-09-14,-1.000000,1.000000,0.361759,0.336002,0.0,1.0,0.592315,0.491404
6,2021-09-17,-0.181860,1.000000,0.560934,0.205673,0.0,1.0,0.241351,0.427902
7,2021-09-19,0.040269,0.326981,0.130907,0.062154,1.0,1.0,1.000000,0.000000
8,2021-09-22,-0.309771,1.000000,0.586798,0.239033,0.0,0.0,0.000000,0.000000
9,2021-09-24,-1.000000,1.000000,0.606467,0.256986,0.0,1.0,0.001497,0.038662
10,2021-09-27,-0.210674,1.000000,0.085159,0.157161,0.0,1.0,0.989181,0.103450
11,2021-09-29,-1.000000,1.000000,0.467599,0.284912,0.0,1.0,0.418164,0.493257

In [66]:
no_request(baguio,'2021-9-01', '2021-9-30','baguio')

,date,min,max,mean,stDev,min_clm,max_clm,mean_clm,stDev_clm
0,2021-09-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2021-09-02,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2021-09-03,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2021-09-04,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2021-09-05,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,2021-09-06,-0.000002,-0.000002,-0.000002,0.0,NaN,NaN,NaN,NaN
6,2021-09-07,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,2021-09-08,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,2021-09-09,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,2021-09-10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,2021-09-11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,2021-09-12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,2021-09-13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,2021-09-14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,2021-09-15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,2021-09-16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,2021-09-17,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,2021-09-18,-0.000009,0.000023,-0.000003,0.000006,NaN,NaN,NaN,NaN
18,2021-09-19,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,2021-09-20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,2021-09-21,0.000003,0.000005,0.000004,0.000001,NaN,NaN,NaN,NaN
21,2021-09-22,-0.0,0.000021,0.000008,0.000007,NaN,NaN,NaN,NaN
22,2021-09-23,0.000001,0.000017,0.00001,0.000008,NaN,NaN,NaN,NaN
23,2021-09-24,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,2021-09-25,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,2021-09-26,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,2021-09-27,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,2021-09-28,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,2021-09-29,0.000029,0.000038,0.000034,0.000004,NaN,NaN,NaN,NaN
29,2021-09-30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## Cagayan de Oro City

In [22]:
ndvi_request(cdo,'2021-9-01', '2021-9-30','cdo')

,date,min,max,mean,stDev,min_clm,max_clm,mean_clm,stDev_clm
0,2021-09-03,-1.000000,1.000000,0.692368,0.293465,0.0,1.0,0.093843,0.291610
1,2021-09-08,-0.253896,0.818534,0.199881,0.208829,1.0,1.0,1.000000,0.000000
2,2021-09-13,-1.000000,1.000000,0.694019,0.273434,0.0,1.0,0.115753,0.319929
3,2021-09-18,-0.498380,0.963432,0.468509,0.167340,0.0,1.0,0.918403,0.273750
4,2021-09-23,-1.000000,1.000000,0.596778,0.323115,0.0,1.0,0.339867,0.473664
5,2021-09-28,-0.779404,1.000000,0.505680,0.238011,0.0,1.0,0.723266,0.447384

In [67]:
no_request(cdo,'2021-9-01', '2021-9-30','cdo')

,date,min,max,mean,stDev,min_clm,max_clm,mean_clm,stDev_clm
0,2021-09-01,-0.0,0.0,-0.0,0.0,NaN,NaN,NaN,NaN
1,2021-09-02,0.000001,0.000028,0.000015,0.000007,NaN,NaN,NaN,NaN
2,2021-09-03,-0.000008,0.000031,0.00001,0.000009,NaN,NaN,NaN,NaN
3,2021-09-04,0.000005,0.00002,0.00001,0.000004,NaN,NaN,NaN,NaN
4,2021-09-05,-0.000008,0.000024,0.000014,0.000008,NaN,NaN,NaN,NaN
5,2021-09-06,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,2021-09-07,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,2021-09-08,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,2021-09-09,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,2021-09-10,-0.000007,0.000026,0.000007,0.000009,NaN,NaN,NaN,NaN
10,2021-09-11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,2021-09-12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,2021-09-13,0.000004,0.000036,0.000018,0.000006,NaN,NaN,NaN,NaN
13,2021-09-14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,2021-09-15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,2021-09-16,0.000014,0.000014,0.000014,0.0,NaN,NaN,NaN,NaN
16,2021-09-17,-0.000023,0.000038,0.00001,0.000013,NaN,NaN,NaN,NaN
17,2021-09-18,-0.000002,0.000059,0.000019,0.000017,NaN,NaN,NaN,NaN
18,2021-09-19,-0.000005,0.000029,0.000018,0.000009,NaN,NaN,NaN,NaN
19,2021-09-20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,2021-09-21,-0.000005,0.000028,0.00001,0.000008,NaN,NaN,NaN,NaN
21,2021-09-22,0.000001,0.000024,0.000017,0.000007,NaN,NaN,NaN,NaN
22,2021-09-23,-0.000004,0.000028,0.00001,0.000007,NaN,NaN,NaN,NaN
23,2021-09-24,-0.0,0.000022,0.000009,0.000008,NaN,NaN,NaN,NaN
24,2021-09-25,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,2021-09-26,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,2021-09-27,-0.000015,0.00004,0.000012,0.00001,NaN,NaN,NaN,NaN
27,2021-09-28,-0.000007,0.000022,0.000011,0.000009,NaN,NaN,NaN,NaN
28,2021-09-29,0.000003,0.000027,0.000013,0.000006,NaN,NaN,NaN,NaN
29,2021-09-30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## Example 3: NO2 Statistics

### Set AOI: NCR

In [18]:
# initialize request to obtain basic stats and histogram values
request_ncr_n = FisRequest(
    data_collection=DataCollection.SENTINEL5P,
    layer='NO2',
    geometry_list=[ncr_geometry],
    time=('2020-02-01', '2020-04-30'),
    resolution='100m',
    config=config
)

ncr_stats_n = request_ncr_n.get_data()

In [19]:
ncr_stats_n

[{'C0': [{'date': '2020-04-30',
    'basicStats': {'min': 5.777318165200995e-06,
     'max': 3.163736255373806e-05,
     'mean': 1.2495069901605659e-05,
     'stDev': 6.840778314637727e-06}},
   {'date': '2020-04-29',
    'basicStats': {'min': 2.3908190996735357e-05,
     'max': 2.3908190996735357e-05,
     'mean': 2.3908190996735357e-05,
     'stDev': 0.0}},
   {'date': '2020-04-28',
    'basicStats': {'min': -5.199191946303472e-06,
     'max': 9.112160478252918e-05,
     'mean': 3.5873422442426126e-05,
     'stDev': 2.3169705863626204e-05}},
   {'date': '2020-04-27',
    'basicStats': {'min': 'NaN', 'max': 'NaN', 'mean': 'NaN', 'stDev': 'NaN'}},
   {'date': '2020-04-26',
    'basicStats': {'min': 5.2092950681981165e-06,
     'max': 2.3117732780519873e-05,
     'mean': 1.4132522702661464e-05,
     'stDev': 4.713930150233507e-06}},
   {'date': '2020-04-25',
    'basicStats': {'min': 1.1267568879702594e-05,
     'max': 3.0842282285448164e-05,
     'mean': 2.0127531996153208e-05,
     'stDev': 6.288879725795974e-06}},
   {'date': '2020-04-24',
    'basicStats': {'min': 7.78921639721375e-06,
     'max': 6.789066537749022e-05,
     'mean': 1.987972654355876e-05,
     'stDev': 9.774500364630578e-06}},
   {'date': '2020-04-23',
    'basicStats': {'min': 1.0942648259515408e-05,
     'max': 4.567719224723987e-05,
     'mean': 2.899808000448429e-05,
     'stDev': 8.892123516097504e-06}},
   {'date': '2020-04-22',
    'basicStats': {'min': -5.011561370338313e-07,
     'max': 4.565368726616725e-05,
     'mean': 2.1228738730494986e-05,
     'stDev': 1.1960459885876357e-05}},
   {'date': '2020-04-21',
    'basicStats': {'min': -2.1111993646627525e-06,
     'max': 6.298648077063262e-05,
     'mean': 2.612263227180345e-05,
     'stDev': 1.596116707421613e-05}},
   {'date': '2020-04-20',
    'basicStats': {'min': 1.1798636478488334e-05,
     'max': 4.9818972911452875e-05,
     'mean': 3.4830317873851715e-05,
     'stDev': 1.3649412022867795e-05}},
   {'date': '2020-04-19',
    'basicStats': {'min': 6.449376087402925e-06,
     'max': 6.449376087402925e-06,
     'mean': 6.449376087402925e-06,
     'stDev': 0.0}},
   {'date': '2020-04-18',
    'basicStats': {'min': 1.111968686018372e-05,
     'max': 4.1661223804112524e-05,
     'mean': 2.857405836202173e-05,
     'stDev': 1.0474134800981375e-05}},
   {'date': '2020-04-17',
    'basicStats': {'min': 2.227257573395036e-05,
     'max': 2.227257573395036e-05,
     'mean': 2.227257573395036e-05,
     'stDev': 0.0}},
   {'date': '2020-04-16',
    'basicStats': {'min': 1.1722971066774335e-05,
     'max': 5.593124296865426e-05,
     'mean': 3.48379314203782e-05,
     'stDev': 9.319018015316705e-06}},
   {'date': '2020-04-15',
    'basicStats': {'min': 2.2345760953612626e-05,
     'max': 6.060698797227815e-05,
     'mean': 4.4622116819470215e-05,
     'stDev': 9.513891680882084e-06}},
   {'date': '2020-04-14',
    'basicStats': {'min': 'NaN', 'max': 'NaN', 'mean': 'NaN', 'stDev': 'NaN'}},
   {'date': '2020-04-13',
    'basicStats': {'min': 1.860850170487538e-05,
     'max': 3.140439002891071e-05,
     'mean': 2.363451048520617e-05,
     'stDev': 4.10893463051459e-06}},
   {'date': '2020-04-12',
    'basicStats': {'min': 'NaN', 'max': 'NaN', 'mean': 'NaN', 'stDev': 'NaN'}},
   {'date': '2020-04-11',
    'basicStats': {'min': 5.780091669294052e-06,
     'max': 7.935374742373824e-05,
     'mean': 2.888484965219209e-05,
     'stDev': 1.0522624168247071e-05}},
   {'date': '2020-04-10',
    'basicStats': {'min': 5.735987997468328e-06,
     'max': 1.1307109161862172e-05,
     'mean': 8.774781359864969e-06,
     'stDev': 2.7740261203026863e-06}},
   {'date': '2020-04-09',
    'basicStats': {'min': 8.314402293763123e-06,
     'max': 3.079012458329089e-05,
     'mean': 1.6878105052275964e-05,
     'stDev': 5.7204494907986446e-06}},
   {'date': '2020-04-08',
    'basicStats': {'min': 1.6080652130767703e-05,
     'max': 3.367157114553265e-05,
     'mean': 2.010705094022936e-05,
     'stDev': 3.86337383959193e-06}},
   {'date': '2020-04-07',
    'basicStats': {'min': 1.7702979675959796e-05,
     'max': 9.05539927771315e-05,
     'mean': 4.75028218159814e-05,
     'stDev': 2.1018553334101775e-05}},
   {'date': '2020-04-06',
    'basicStats': {'min': 7.472606739611365e-06,
     'max': 4.5875371142756194e-05,
     'mean': 2.2889696327409918e-05,
     'stDev': 1.0892871266093402e-05}},
   {'date': '2020-04-05',
    'basicStats': {'min': 9.012746886583045e-06,
     'max': 5.167418566998094e-05,
     'mean': 2.828360931980436e-05,
     'stDev': 1.1123064923663174e-05}},
   {'date': '2020-04-03',
    'basicStats': {'min': 1.0221512638963759e-05,
     'max': 4.7264493332477286e-05,
     'mean': 3.1981442052756166e-05,
     'stDev': 8.527741639138338e-06}},
   {'date': '2020-04-02',
    'basicStats': {'min': 2.9808745694026584e-06,
     'max': 2.5725454179337248e-05,
     'mean': 1.2317345704772601e-05,
     'stDev': 3.7246973458050774e-06}},
   {'date': '2020-04-01',
    'basicStats': {'min': 1.040677943819901e-05,
     'max': 6.571735866600648e-05,
     'mean': 2.8133416085690377e-05,
     'stDev': 1.2049693289589946e-05}},
   {'date': '2020-03-31',
    'basicStats': {'min': 1.0195175264016143e-06,
     'max': 6.389981717802584e-05,
     'mean': 3.115251697400195e-05,
     'stDev': 1.4266432619106515e-05}},
   {'date': '2020-03-30',
    'basicStats': {'min': 'NaN', 'max': 'NaN', 'mean': 'NaN', 'stDev': 'NaN'}},
   {'date': '2020-03-29',
    'basicStats': {'min': 7.294411261682399e-06,
     'max': 2.8190130251459777e-05,
     'mean': 1.1331160813075704e-05,
     'stDev': 3.984366750172955e-06}},
   {'date': '2020-03-28',
    'basicStats': {'min': 3.887903403665405e-06,
     'max': 5.8959743910236284e-05,
     'mean': 2.79790826300224e-05,
     'stDev': 1.661870966533007e-05}},
   {'date': '2020-03-27',
    'basicStats': {'min': 3.2223863399849506e-06,
     'max': 4.203634671284817e-05,
     'mean': 2.30638504102817e-05,
     'stDev': 9.291362707228297e-06}},
   {'date': '2020-03-26',
    'basicStats': {'min': 8.282163435069378e-06,
     'max': 4.876984530710615e-05,
     'mean': 2.9248274783322217e-05,
     'stDev': 9.725589028391298e-06}},
   {'date': '2020-03-25',
    'basicStats': {'min': 5.880722255824367e-06,
     'max': 3.862535595544614e-05,
     'mean': 2.0002493837622263e-05,
     'stDev': 8.134256329391803e-06}},
   {'date': '2020-03-24',
    'basicStats': {'min': 2.631981487866142e-06,
     'max': 3.795395605266094e-05,
     'mean': 1.7233940091753923e-05,
     'stDev': 1.143010089822812e-05}},
   {'date': '2020-03-23',
    'basicStats': {'min': -8.203562060771219e-07,
     'max': 9.332601621281356e-05,
     'mean': 3.965070653323608e-05,
     'stDev': 2.3320142051929552e-05}},
   {'date': '2020-03-22',
    'basicStats': {'min': -6.255289918044582e-06,
     'max': 4.51701162091922e-05,
     'mean': 1.5783130270611286e-05,
     'stDev': 1.3028256688221085e-05}},
   {'date': '2020-03-21',
    'basicStats': {'min': 6.809490969317267e-06,
     'max': 5.2085368224652484e-05,
     'mean': 2.9007726247362983e-05,
     'stDev': 1.0932264680174989e-05}},
   {'date': '2020-03-20',
    'basicStats': {'min': -7.985293450474273e-06,
     'max': 5.074902219348587e-05,
     'mean': 2.15499048024955e-05,
     'stDev': 1.34732820435959e-05}},
   {'date': '2020-03-19',
    'basicStats': {'min': 8.472106856061146e-06,
     'max': 4.010633347206749e-05,
     'mean': 2.3068203191291937e-05,
     'stDev': 9.874645238198733e-06}},
   {'date': '2020-03-18',
    'basicStats': {'min': 1.294017147301929e-05,
     'max': 3.659604044514708e-05,
     'mean': 2.452012947026815e-05,
     'stDev': 8.944014924509432e-06}},
   {'date': '2020-03-17',
    'basicStats': {'min': 2.1396012016339228e-05,
     'max': 2.1396012016339228e-05,
     'mean': 2.1396012016339228e-05,
     'stDev': 0.0}},
   {'date': '2020-03-16',
    'basicStats': {'min': 'NaN', 'max': 'NaN', 'mean': 'NaN', 'stDev': 'NaN'}},
   {'date': '2020-03-15',
    'basicStats': {'min': 2.65033795585623e-05,
     'max': 6.358934479067102e-05,
     'mean': 4.232749377649814e-05,
     'stDev': 8.017625537743699e-06}},
   {'date': '2020-03-14',
    'basicStats': {'min': 2.7427784516476095e-05,
     'max': 0.00011025111598428339,
     'mean': 6.854532108468433e-05,
     'stDev': 2.232250506652791e-05}},
   {'date': '2020-03-13',
    'basicStats': {'min': 1.4289763385022525e-05,
     'max': 6.08132868364919e-05,
     'mean': 3.7535270282395734e-05,
     'stDev': 1.6045523271489916e-05}},
   {'date': '2020-03-12',
    'basicStats': {'min': 1.2233048437337857e-05,
     'max': 5.356584006221965e-05,
     'mean': 3.054841691596256e-05,
     'stDev': 1.2316146872839291e-05}},
   {'date': '2020-03-11',
    'basicStats': {'min': 1.2788783351425081e-05,
     'max': 3.170065247104503e-05,
     'mean': 2.247010967668971e-05,
     'stDev': 5.210513781694522e-06}},
   {'date': '2020-03-10',
    'basicStats': {'min': 5.297202369547449e-05,
     'max': 0.00022031004482414573,
     'mean': 0.0001184723113282692,
     'stDev': 4.3237414043779954e-05}},
   {'date': '2020-03-09',
    'basicStats': {'min': 1.7755433873389848e-05,
     'max': 9.449219214729965e-05,
     'mean': 6.144135297741447e-05,
     'stDev': 1.9003398771539197e-05}},
   {'date': '2020-03-08',
    'basicStats': {'min': 3.982235648436472e-05,
     'max': 0.00010873597057070583,
     'mean': 7.592050639886738e-05,
     'stDev': 1.919061285713615e-05}},
   {'date': '2020-03-07',
    'basicStats': {'min': 3.655851833173074e-05,
     'max': 0.00015240641369018704,
     'mean': 0.00010134196759926315,
     'stDev': 5.092243474040915e-05}},
   {'date': '2020-03-06',
    'basicStats': {'min': 4.229129899613326e-06,
     'max': 0.00022567309497389942,
     'mean': 4.2326863719341634e-05,
     'stDev': 3.3730930788743936e-05}},
   {'date': '2020-03-05',
    'basicStats': {'min': 2.634259726619348e-05,
     'max': 0.0005960292764939368,
     'mean': 0.0001993223816248997,
     'stDev': 0.00014417972283427147}},
   {'date': '2020-03-04',
    'basicStats': {'min': 'NaN', 'max': 'NaN', 'mean': 'NaN', 'stDev': 'NaN'}},
   {'date': '2020-03-03',
    'basicStats': {'min': 1.2621402674994897e-05,
     'max': 3.4426600905135274e-05,
     'mean': 2.1675275828807472e-05,
     'stDev': 6.993020519579394e-06}},
   {'date': '2020-03-02',
    'basicStats': {'min': 2.0887977370875888e-05,
     'max': 0.00014846281555946916,
     'mean': 6.414414861991047e-05,
     'stDev': 2.9553121562321e-05}},
   {'date': '2020-03-01',
    'basicStats': {'min': 3.1027486784296343e-06,
     'max': 6.385616870829836e-05,
     'mean': 2.0518641142212694e-05,
     'stDev': 1.92345915620834e-05}},
   {'date': '2020-02-29',
    'basicStats': {'min': 3.880477379425429e-06,
     'max': 0.00016662008420098573,
     'mean': 4.803897762474788e-05,
     'stDev': 4.038345020196014e-05}},
   {'date': '2020-02-28',
    'basicStats': {'min': -2.761739779089112e-06,
     'max': 5.893944762647152e-05,
     'mean': 3.655141807792427e-05,
     'stDev': 1.643290927079574e-05}},
   {'date': '2020-02-27',
    'basicStats': {'min': 9.927138307830319e-06,
     'max': 3.4219076042063534e-05,
     'mean': 2.361487486024034e-05,
     'stDev': 7.639806481692882e-06}},
   {'date': '2020-02-26',
    'basicStats': {'min': 1.1581252692849375e-05,
     'max': 2.473177300998941e-05,
     'mean': 1.5983333646468285e-05,
     'stDev': 6.205750421669105e-06}},
   {'date': '2020-02-25',
    'basicStats': {'min': 5.7097189198884735e-08,
     'max': 4.3505187932169065e-05,
     'mean': 2.9968229742769e-05,
     'stDev': 1.1019645140293727e-05}},
   {'date': '2020-02-24',
    'basicStats': {'min': 1.0946683687507175e-05,
     'max': 2.117993608408142e-05,
     'mean': 1.502479412162821e-05,
     'stDev': 4.8719364799117825e-06}},
   {'date': '2020-02-23',
    'basicStats': {'min': 3.905478024535114e-06,
     'max': 3.549022221704945e-05,
     'mean': 2.3025959914573458e-05,
     'stDev': 8.663984733094461e-06}},
   {'date': '2020-02-22',
    'basicStats': {'min': 1.374170824419707e-05,
     'max': 0.00012204693484818563,
     'mean': 5.670673325525528e-05,
     'stDev': 3.352822853536049e-05}},
   {'date': '2020-02-21',
    'basicStats': {'min': 5.169939868210349e-06,
     'max': 7.274212111951783e-05,
     'mean': 2.566926873011219e-05,
     'stDev': 1.1674795290216447e-05}},
   {'date': '2020-02-20',
    'basicStats': {'min': 9.369449799123686e-06,
     'max': 9.130063699558377e-05,
     'mean': 4.086210442866068e-05,
     'stDev': 2.4852381800684677e-05}},
   {'date': '2020-02-19',
    'basicStats': {'min': 6.023357855156064e-06,
     'max': 8.416752825723961e-05,
     'mean': 3.846557529347998e-05,
     'stDev': 1.8798153680814726e-05}},
   {'date': '2020-02-18',
    'basicStats': {'min': 8.058967978286091e-06,
     'max': 8.881513349479064e-05,
     'mean': 3.4198741529276296e-05,
     'stDev': 1.5367748888049078e-05}},
   {'date': '2020-02-17',
    'basicStats': {'min': 'NaN', 'max': 'NaN', 'mean': 'NaN', 'stDev': 'NaN'}},
   {'date': '2020-02-16',
    'basicStats': {'min': 2.004732596105896e-05,
     'max': 6.98058502166532e-05,
     'mean': 4.153611409233942e-05,
     'stDev': 1.6812999342481662e-05}},
   {'date': '2020-02-15',
    'basicStats': {'min': 1.217286626342684e-05,
     'max': 7.471763092326e-05,
     'mean': 3.908147496518708e-05,
     'stDev': 1.9209511345150757e-05}},
   {'date': '2020-02-14',
    'basicStats': {'min': 1.0650920557964128e-05,
     'max': 8.892915502656251e-05,
     'mean': 3.828123731359101e-05,
     'stDev': 1.979507796226964e-05}},
   {'date': '2020-02-13',
    'basicStats': {'min': 'NaN', 'max': 'NaN', 'mean': 'NaN', 'stDev': 'NaN'}},
   {'date': '2020-02-12',
    'basicStats': {'min': 1.4502856174658518e-05,
     'max': 9.26172433537431e-05,
     'mean': 4.850804859143563e-05,
     'stDev': 2.2680686640076028e-05}},
   {'date': '2020-02-11',
    'basicStats': {'min': 2.6352311124355765e-06,
     'max': 7.014528819127008e-05,
     'mean': 4.107734536493062e-05,
     'stDev': 1.8033317844621887e-05}},
   {'date': '2020-02-10',
    'basicStats': {'min': 'NaN', 'max': 'NaN', 'mean': 'NaN', 'stDev': 'NaN'}},
   {'date': '2020-02-09',
    'basicStats': {'min': 'NaN', 'max': 'NaN', 'mean': 'NaN', 'stDev': 'NaN'}},
   {'date': '2020-02-08',
    'basicStats': {'min': 1.7676595234661363e-05,
     'max': 4.24785066570621e-05,
     'mean': 3.882348813165566e-05,
     'stDev': 8.791603112817356e-06}},
   {'date': '2020-02-07',
    'basicStats': {'min': 'NaN', 'max': 'NaN', 'mean': 'NaN', 'stDev': 'NaN'}},
   {'date': '2020-02-06',
    'basicStats': {'min': 'NaN', 'max': 'NaN', 'mean': 'NaN', 'stDev': 'NaN'}},
   {'date': '2020-02-05',
    'basicStats': {'min': 1.940951551659964e-05,
     'max': 4.123349572182633e-05,
     'mean': 2.7084093300903218e-05,
     'stDev': 7.069071440280777e-06}},
   {'date': '2020-02-04',
    'basicStats': {'min': 1.351293485640781e-05,
     'max': 5.6977951317094266e-05,
     'mean': 3.188201653689868e-05,
     'stDev': 8.736396556330319e-06}},
   {'date': '2020-02-03',
    'basicStats': {'min': 'NaN', 'max': 'NaN', 'mean': 'NaN', 'stDev': 'NaN'}},
   {'date': '2020-02-02',
    'basicStats': {'min': 1.2963011613464914e-05,
     'max': 3.517211735015735e-05,
     'mean': 2.4710337678281176e-05,
     'stDev': 7.552903539966107e-06}},
   {'date': '2020-02-01',
    'basicStats': {'min': 1.969518962141592e-05,
     'max': 5.892182525712997e-05,
     'mean': 3.786076300946369e-05,
     'stDev': 1.2217946235194733e-05}}]}]

In [20]:
ncr_n = clean_df(ncr_stats_n)
ncr_n_df = ncr_n[ncr_n.columns[~ncr_n.columns.str.endswith('_clm')]]
ncr_n_df

         date          min          max         mean        stDev
0  2020-02-01  1.96952e-05  5.89218e-05  3.78608e-05  1.22179e-05
1  2020-02-02   1.2963e-05  3.51721e-05  2.47103e-05   7.5529e-06
2  2020-02-03          NaN          NaN          NaN          NaN
3  2020-02-04  1.35129e-05   5.6978e-05   3.1882e-05   8.7364e-06
4  2020-02-05  1.94095e-05  4.12335e-05  2.70841e-05  7.06907e-06
..        ...          ...          ...          ...          ...
84 2020-04-26   5.2093e-06  2.31177e-05  1.41325e-05  4.71393e-06
85 2020-04-27          NaN          NaN          NaN          NaN
86 2020-04-28 -5.19919e-06  9.11216e-05  3.58734e-05  2.31697e-05
87 2020-04-29  2.39082e-05  2.39082e-05  2.39082e-05            0
88 2020-04-30  5.77732e-06  3.16374e-05  1.24951e-05  6.84078e-06

[89 rows x 5 columns]

In [21]:
ncr_n_df.to_csv('ncr-nO2.csv', index=False)